In [3]:
data = pd.read_csv('공공자전거 대여소 정보(23.06월 기준).csv',encoding='EUC-KR')
data

,대여소\n번호,보관소(대여소)명,자치구,상세주소,위도,경도,설치\n시기,거치\n대수,거치\n대수.1,운영\n방식
0,301,경복궁역 7번출구 앞,종로구,서울특별시 종로구 사직로 지하130 경복궁역 7번출구 앞,37.575794,126.971451,2015-10-07,20.0,20.0,QR
1,302,경복궁역 4번출구 뒤,종로구,서울특별시 종로구 사직로 지하130 경복궁역 4번출구 뒤,37.575947,126.974060,2015-10-07,12.0,12.0,QR
2,303,광화문역 1번출구 앞,종로구,서울특별시 종로구 세종대로 지하189 세종로공원,37.571770,126.974663,2015-10-07,8.0,8.0,QR
3,305,종로구청 옆,종로구,서울특별시 종로구 세종로 84-1,37.572559,126.978332,2015-01-07,16.0,16.0,QR
4,307,서울역사박물관 앞,종로구,서울특별시 종로구 새문안로 55 서울역사박물관 앞,37.570000,126.971100,2015-10-07,11.0,11.0,QR
...,...,...,...,...,...,...,...,...,...,...
2744,3699,상일파출소 옆,강동구,강동구 상일동 520-1,37.556553,127.165878,2022-06-21,NaN,15.0,QR
2745,3700,강변그대가리버뷰 입구 맞은편,강동구,강동구 천호동 250-7,37.548164,127.122574,2022-07-08,NaN,8.0,QR
2746,3701,방아삼거리,강동구,강동구 둔촌동 118-2,37.523281,127.146133,2022-10-12,NaN,8.0,QR
2747,4951,강동농협 버스정류소 앞(광채빌라),강동구,강동구 암사동 488-21,37.547966,127.135162,2022-09-29,NaN,5.0,QR
2748,4952,천호시장 버스정류소 옆,강동구,강동구 천호동 397-465,37.541466,127.130257,2023-01-18,NaN,5.0,QR

In [5]:
data['거치\n대수'].value_counts(dropna=False)

거치\n대수
NaN     1434
10.0     601
15.0     179
20.0     123
8.0       80
12.0      52
13.0      41
7.0       40
9.0       38
14.0      33
25.0      21
5.0       15
6.0       14
17.0      11
30.0      11
16.0      10
11.0       9
18.0       8
23.0       5
19.0       5
22.0       4
40.0       3
21.0       3
26.0       3
24.0       2
45.0       1
27.0       1
32.0       1
31.0       1
Name: count, dtype: int64

In [7]:
data['거치\n대수'].isna()

0       False
1       False
2       False
3       False
4       False
        ...
2744     True
2745     True
2746     True
2747     True
2748     True
Name: 거치\n대수, Length: 2749, dtype: bool

In [9]:
data.isna().sum()

대여소\n번호         0
보관소(대여소)명       0
자치구             0
상세주소            0
위도              0
경도              0
설치\n시기          0
거치\n대수       1434
거치\n대수.1     1167
운영\n방식          0
dtype: int64

In [11]:
data.dropna(subset=['거치\n대수','거치\n대수.1'])

,대여소\n번호,보관소(대여소)명,자치구,상세주소,위도,경도,설치\n시기,거치\n대수,거치\n대수.1,운영\n방식
0,301,경복궁역 7번출구 앞,종로구,서울특별시 종로구 사직로 지하130 경복궁역 7번출구 앞,37.575794,126.971451,2015-10-07,20.0,20.0,QR
1,302,경복궁역 4번출구 뒤,종로구,서울특별시 종로구 사직로 지하130 경복궁역 4번출구 뒤,37.575947,126.974060,2015-10-07,12.0,12.0,QR
2,303,광화문역 1번출구 앞,종로구,서울특별시 종로구 세종대로 지하189 세종로공원,37.571770,126.974663,2015-10-07,8.0,8.0,QR
3,305,종로구청 옆,종로구,서울특별시 종로구 세종로 84-1,37.572559,126.978332,2015-01-07,16.0,16.0,QR
4,307,서울역사박물관 앞,종로구,서울특별시 종로구 새문안로 55 서울역사박물관 앞,37.570000,126.971100,2015-10-07,11.0,11.0,QR
...,...,...,...,...,...,...,...,...,...,...
1843,270,증권거래소후문교차로,영등포구,서울특별시 영등포구 여의나루로 76,37.522343,126.927101,2016-07-06,10.0,10.0,QR
1848,278,쌍용플레티넘오피스텔,영등포구,서울특별시 영등포구 도영로 18,37.507931,126.895233,2017-11-28,10.0,10.0,QR
2290,2356,강남구청,강남구,서울특별시 강남구 학동로 지하 346,37.518070,127.047119,2017-08-21,10.0,10.0,QR
2463,1271,송파도서관,송파구,서울특별시 송파구 동남로 263,37.499985,127.135391,2017-11-01,15.0,15.0,QR
2657,1033,고덕동 아남아파트,강동구,서울특별시 고덕동 673,37.557934,127.144768,2017-11-01,10.0,17.0,QR

In [13]:
data.dropna(axis = 0,how = 'any')

,대여소\n번호,보관소(대여소)명,자치구,상세주소,위도,경도,설치\n시기,거치\n대수,거치\n대수.1,운영\n방식
0,301,경복궁역 7번출구 앞,종로구,서울특별시 종로구 사직로 지하130 경복궁역 7번출구 앞,37.575794,126.971451,2015-10-07,20.0,20.0,QR
1,302,경복궁역 4번출구 뒤,종로구,서울특별시 종로구 사직로 지하130 경복궁역 4번출구 뒤,37.575947,126.974060,2015-10-07,12.0,12.0,QR
2,303,광화문역 1번출구 앞,종로구,서울특별시 종로구 세종대로 지하189 세종로공원,37.571770,126.974663,2015-10-07,8.0,8.0,QR
3,305,종로구청 옆,종로구,서울특별시 종로구 세종로 84-1,37.572559,126.978332,2015-01-07,16.0,16.0,QR
4,307,서울역사박물관 앞,종로구,서울특별시 종로구 새문안로 55 서울역사박물관 앞,37.570000,126.971100,2015-10-07,11.0,11.0,QR
...,...,...,...,...,...,...,...,...,...,...
1843,270,증권거래소후문교차로,영등포구,서울특별시 영등포구 여의나루로 76,37.522343,126.927101,2016-07-06,10.0,10.0,QR
1848,278,쌍용플레티넘오피스텔,영등포구,서울특별시 영등포구 도영로 18,37.507931,126.895233,2017-11-28,10.0,10.0,QR
2290,2356,강남구청,강남구,서울특별시 강남구 학동로 지하 346,37.518070,127.047119,2017-08-21,10.0,10.0,QR
2463,1271,송파도서관,송파구,서울특별시 송파구 동남로 263,37.499985,127.135391,2017-11-01,15.0,15.0,QR
2657,1033,고덕동 아남아파트,강동구,서울특별시 고덕동 673,37.557934,127.144768,2017-11-01,10.0,17.0,QR

In [15]:
data['거치\n대수'].value_counts().sort_index()

거치\n대수
5.0      15
6.0      14
7.0      40
8.0      80
9.0      38
10.0    601
11.0      9
12.0     52
13.0     41
14.0     33
15.0    179
16.0     10
17.0     11
18.0      8
19.0      5
20.0    123
21.0      3
22.0      4
23.0      5
24.0      2
25.0     21
26.0      3
27.0      1
30.0     11
31.0      1
32.0      1
40.0      3
45.0      1
Name: count, dtype: int64

In [17]:
data.duplicated(['거치\n대수'])

0       False
1       False
2       False
3       False
4       False
        ...
2744     True
2745     True
2746     True
2747     True
2748     True
Length: 2749, dtype: bool

In [19]:
data.duplicated(['거치\n대수'])

0       False
1       False
2       False
3       False
4       False
        ...
2744     True
2745     True
2746     True
2747     True
2748     True
Length: 2749, dtype: bool

In [21]:
data.drop_duplicates(subset = ['거치\n대수','거치\n대수.1'],keep=False)

,대여소\n번호,보관소(대여소)명,자치구,상세주소,위도,경도,설치\n시기,거치\n대수,거치\n대수.1,운영\n방식
5,308,광화문 S타워 앞,종로구,서울특별시 종로구 새문안로 82 광화문S타워 앞,37.569969,126.973938,2015-10-07,20.0,31.0,QR
9,326,안국역 5번출구 앞,종로구,서울특별시 종로구 율곡로 지하62 안국역 5번출구 앞,37.576241,126.986160,2015-10-07,18.0,15.0,QR
20,342,대학로 마로니에공원,종로구,서울특별시 종로구 대학로 104 대학로 마로니에공원,37.579784,127.002533,2015-10-07,15.0,22.0,QR
21,343,예일빌딩(율곡로) 앞,종로구,서울특별시 종로구 충신동 60,37.575611,127.004700,2015-10-07,12.0,6.0,QR
38,367,독립문역 3-1번출구,종로구,서울특별시 종로구 무악동 41-7 독립문역 3번출구 뒤,37.573849,126.958694,2016-06-01,8.0,13.0,QR
50,450,효자동 삼거리,종로구,서울특별시 종로구 효자로13길 45 종로구 궁정동 98-2,37.583603,126.972549,2017-09-07,NaN,51.0,QR
58,458,광화문역 5번출구,종로구,서울특별시 종로구 세종대로 152 일민미술관,37.569893,126.977570,2018-08-31,21.0,NaN,LCD
103,300,정동사거리,중구,서울특별시 중구 정동길 2-1 정동사거리,37.568050,126.969231,2015-10-07,7.0,6.0,QR
104,310,청계광장 옆,중구,서울특별시 중구 세종대로 136 청계광장 옆,37.568878,126.977470,2015-10-07,13.0,8.0,QR
106,320,을지로입구역 4번출구 앞,중구,서울특별시 중구 을지로 55 명동금융센터 앞,37.566223,126.983589,2015-10-07,20.0,17.0,QR
203,815,LIG강촌아파트 103동앞,용산구,서울특별시 용산구 이촌동301-5 LIG강촌아파트 103동앞,37.518509,126.978798,2016-06-29,30.0,30.0,QR
214,829,한강대교 북단 교차로,용산구,서울특별시 용산구 한강대로 23 베르가모앞,37.522930,126.961693,2017-11-28,40.0,NaN,LCD
226,843,이태원관광특구B(용산구청쪽),용산구,서울특별시 용산구 이태원로 134 녹사평역 광장,37.533798,126.988670,2018-10-07,10.0,19.0,QR
302,520,상왕십리역 4번 출구 앞,성동구,서울특별시 성동구 하왕십리동 960-3 상왕십리역 4번 출구 앞,37.563858,127.030319,2016-06-29,10.0,7.0,QR
304,522,금호역 1번출구 앞,성동구,서울특별시 성동구 금호동3가 1575-3 금호역 1번출구 앞,37.548641,127.016426,2016-06-29,9.0,9.0,QR
309,529,장한평역 8번 출구 앞,성동구,서울특별시 성동구 용답동 224-3 장안평역 8번 출구 앞,37.561371,127.063660,2016-06-29,15.0,8.0,QR
321,559,왕십리역 4번 출구 건너편,성동구,서울특별시 성동구 왕십리광장로 10-1 왕십리역 4번 출구 건너편,37.561096,127.036797,2016-07-06,10.0,13.0,QR
327,565,옥수역 3번출구,성동구,서울특별시 성동구 옥수동 192-2,37.541367,127.017761,2016-07-06,15.0,19.0,QR
334,583,청계천 생태교실 앞,성동구,서울특별시 성동구 마장로39길 51 청계천 생태교실 앞,37.567970,127.046890,2016-07-06,20.0,5.0,LCD
401,501,광진구의회 앞,광진구,서울특별시 광진구 능동로 76 광진구의회 앞,37.537308,127.070351,2015-10-07,21.0,30.0,QR
402,502,뚝섬유원지역 1번출구 앞,광진구,서울특별시 광진구 능동로 10 뚝섬유원지역 1번출구 앞,37.531860,127.067192,2015-10-07,17.0,33.0,QR
405,516,광진메디칼 앞,광진구,서울특별시 광진구 광나루로 355 광진메디컬앞,37.548405,127.069367,2015-10-07,5.0,10.0,QR
408,542,강변역 4번출구 뒤,광진구,"서울특별시 광진구 구의동 546-6 강변역 1,4번 출구 아래",37.535824,127.094162,2016-06-29,19.0,19.0,QR
420,574,아차산역4번출구,광진구,서울특별시 광진구 능동로 216 아차산역4번출구,37.551849,127.088982,2016-07-06,45.0,NaN,LCD
456,3882,자양2동 주민센터,광진구,서울특별시 광진구 자양로3가길 28,37.528793,127.084633,2021-07-23,NaN,3.0,QR
479,626,군자교 서측 녹지대,동대문구,서울특별시 동대문구 장한로6길 95 군자교녹지대 동측 앞,37.561153,127.070969,2016-07-06,17.0,17.0,QR
793,1720,도봉구청 옆(중랑천변),도봉구,서울특별시 도봉구 마들로 656 도봉구청 옆(중랑천변),37.668671,127.047981,2017-11-01,27.0,NaN,LCD
1007,917,녹번역 3번출구,은평구,서울특별시 은평구 은평로 234-2 구두수선대,37.600780,126.935211,2016-09-02,9.0,10.0,QR
1017,931,역촌파출소,은평구,서울특별시 은평구 역촌동 45-34 역촌파출소,37.604736,126.915337,2016-09-02,32.0,NaN,LCD
1103,159,이대역 4번 출구,서대문구,서울특별시 서대문구 대현동 60-11,37.556953,126.946343,2016-06-29,7.0,5.0,QR
1212,186,월드컵공원,마포구,서울특별시 마포구 하늘공원로 108-1,37.563965,126.898209,2016-07-06,40.0,40.0,QR
1231,418,월드컵경기장역 3번출구 옆,마포구,서울특별시 마포구 월드컵로 지하240,37.570721,126.898979,2015-10-07,10.0,20.0,QR
1232,419,홈플러스 앞,마포구,서울특별시 마포구 월드컵로 240,37.568420,126.899429,2015-10-07,21.0,21.0,QR
1233,420,서울시 공공자전거 상암센터,마포구,서울특별시 마포구 월드컵북로47길 10,37.566246,126.896179,2015-10-07,40.0,37.0,QR
1410,1110,공항중학교앞,강서구,서울특별시 강서구 방화대로 241,37.562202,126.816246,2017-06-20,10.0,15.0,QR
1474,1193,마곡센트럴타워 1차,강서구,강서구 마곡동 727-1136,37.559471,126.832077,2018-11-20,15.0,51.0,QR
1479,1198,LG 사이언스파크,강서구,강서구 마곡동 727-925,37.562550,126.827438,2018-11-20,31.0,NaN,LCD
1496,2717,LG유플러스 마곡사옥,강서구,강서구 마곡중앙8로 71,37.561337,126.833900,2020-03-15,NaN,55.0,QR
1789,207,여의나루역 1번출구 앞,영등포구,서울특별시 영등포구 여의동로 지하343,37.527157,126.931900,2015-09-17,NaN,46.0,QR
1926,5855,하이투자증권 앞,영등포구,여의대로 66,37.524643,126.923424,2022-06-09,NaN,31.0,QR
2441,1243,문정 법조단지7,송파구,서울특별시 송파구 법원로 101,37.484531,127.120163,2017-06-27,NaN,29.0,QR
2528,2652,송파 레미니스1단지 102동 앞,송파구,오금동 96,37.508831,127.134262,2020-01-15,NaN,41.0,QR
2576,4457,아산병원 기숙사 부근,송파구,올림픽로43길 88,37.524780,127.109131,2021-01-04,NaN,50.0,QR
2657,1033,고덕동 아남아파트,강동구,서울특별시 고덕동 673,37.557934,127.144768,2017-11-01,10.0,17.0,QR